# Generated by Django 4.2.5 on 2023-09-19 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mb_email', models.EmailField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('mb_phone', models.CharField(max_length=20)),
                ('mb_name', models.CharField(max_length=50)),
                ('mb_nickname', models.CharField(max_length=50)),
                ('mb_certify', models.BooleanField(default=False)),
                ('mb_services_agree', models.BooleanField(default=False)),
                ('mb_marketing_agree', models.BooleanField(default=False)),
                ('mb_privacy_agree', models.BooleanField(default=False)),
                ('mb_social_type', models.CharField(max_length=1)),
                ('mb_level', models.SmallIntegerField(default=1)),
                ('mb_birth', models.CharField(blank=True, max_length=8)),
                ('mb_gender', models.CharField(blank=True, max_length=1)),
                ('mb_profile_image', models.FileField(blank=True, upload_to='')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_no', models.BigIntegerField(unique=True)),
                ('mb_email', models.EmailField(max_length=255, unique=True)),
                ('ep_description', models.TextField()),
                ('ep_hours', models.TextField()),
                ('ep_education', models.TextField()),
                ('ep_license', models.TextField()),
                ('ep_career', models.TextField()),
                ('ep_product', models.TextField()),
                ('ep_product_options', models.TextField()),
            ],
            options={
                'db_table': 'expert',
            },
        ),
    ]
